ci:
  autoupdate_commit_msg: "chore: [pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-json
    - id: check-yaml
    - id: check-toml
    - id: check-xml
    - id: debug-statements
    - id: end-of-file-fixer
      # exclude generated files
      exclude: ^validation/|\.dtd$|\.json$|\.xml$
    - id: mixed-line-ending
    - id: requirements-txt-fixer
      exclude: lower-bound-requirements.txt
    - id: trailing-whitespace
      # exclude generated files
      exclude: ^validation/|\.dtd$|\.xml$
