name: CI

on:
  push:
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Inject Lorem Ipsum
      run: |
        echo "\usepackage{lipsum}" >> latex/packages.tex
        echo "\lipsum[1-5]" >> src/acknowledgements.tex
        echo "\lipsum[6-7]" >> src/abstract.tex
        echo "\lipsum[8-11]" >> src/introduction.tex
    - name: Compile Template in Place
      uses: docker://xucheng/texlive-full:latest
      with:
        entrypoint: /bin/sh
        args: |
          -c "\
          apk --no-cache add make && \
          make final && \
          ls -lhtra"
    - name: Checkout repo again for run as user
      uses: actions/checkout@v2
      with:
        path: run_as_user/Dedman-Thesis-Latex-Template
    - name: Prepare for run as user
      run: |
        cd run_as_user
        git init .
        bash Dedman-Thesis-Latex-Template/update_template.sh install
        ls -lhtra
    - name: Compile Template as User
      uses: docker://xucheng/texlive-full:latest
      with:
        entrypoint: /bin/sh
        args: |
          -c "\
          apk --no-cache add make && \
          cd run_as_user && \
          make final && \
          ls -lhtra"
    - name: Make arXiv submission tar.gz
      uses: docker://xucheng/texlive-full:latest
      with:
        entrypoint: /bin/sh
        args: |
          -c "\
          apk --no-cache add make tar && \
          cd run_as_user && \
          make document && \
          make arXiv && \
          ls -lhtra && \
          tar -tf submit_to_arXiv.tar.gz"
