name: CI

on:
  push:
  pull_request:
  # Run daily at 0:01 UTC
  schedule:
  - cron:  '1 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Inject Lorem Ipsum
      run: |
        echo "\usepackage{lipsum}" >> latex/packages.tex
        echo "\lipsum[1-5]" >> src/acknowledgements.tex
        echo "\lipsum[6-7]" >> src/abstract.tex
        echo "\lipsum[8-11]" >> src/introduction.tex
    - name: Compile Template in Place
      uses: xu-cheng/latex-action@1.3.0
      with:
        extra_system_packages: "make"
        pre_compile: "make final"
        root_file: user_thesis.tex # root_file is required by latex-action
        post_compile: "ls -lhtra"
    - name: Checkout repo again for run as user
      uses: actions/checkout@v2
      with:
        path: run_as_user/Dedman-Thesis-Latex-Template
    - name: Prepare for run as user
      run: |
        cd run_as_user
        git init .
        bash Dedman-Thesis-Latex-Template/update_template.sh install
        ls -lhtra
    - name: Compile Template as User
      uses: xu-cheng/latex-action@1.3.0
      with:
        working_directory: run_as_user
        extra_system_packages: "make"
        pre_compile: "make final"
        root_file: user_thesis.tex # root_file is required by latex-action
        post_compile: "ls -lhtra"
    - name: Make arXiv submission tar.gz
      uses: xu-cheng/latex-action@1.3.0
      with:
        working_directory: run_as_user
        extra_system_packages: "make tar"
        pre_compile: "make document"
        root_file: user_thesis.tex # root_file is required by latex-action
        post_compile: "make arXiv && ls -lhtra && tar -tf submit_to_arXiv.tar.gz"
