name: Publish docs

on:
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Inject Lorem Ipsum
      run: |
        echo "\usepackage{lipsum}" >> latex/packages.tex
        echo "\lipsum[1-5]" >> src/acknowledgements.tex
        echo "\lipsum[6-7]" >> src/abstract.tex
        echo "\lipsum[8-11]" >> src/introduction.tex
    - name: Compile LaTeX document
      uses: docker://xucheng/texlive-full:latest
      with:
        entrypoint: /bin/sh
        args: |
          -c "\
          apk --no-cache add make && \
          make final && \
          ls -lhtra"
    - name: Setup docs for deployment
      run: |
        mkdir -p docs/_build/template
        cp README.md docs/_build/
        cp user_thesis.pdf docs/_build/template/template.pdf
    - name: Deploy docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build
        enable_jekyll: true # for README render
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
